artifacts_root: artifacts


data_ingestion:
  root_dir : artifacts/data_ingestion
  bucket_name : cricket-frame-dataset
  bucket_folder_name: Dataset


model_training:
  root_dir : artifacts/models
  training_data_yaml_dir : ../../../artifacts/data_ingestion/data.yaml
  yolo_pretrained_weight_name : yolov8x.pt
  trained_model_path : artifacts/models/best.pt
  onnx_model_path : artifacts/models/best.onnx

mlflow_config:
  tracking_uri : https://dagshub.com/rxhith/yolo-pipeline.mlflow
  experiment_name : KSEB
  tracking_username : rxhith
  tracking_password : 1ba4abcbe0ba7d69d7a2c0d98f5cfed7826f6833



  
