artifacts_root: artifacts


data_ingestion:
  root_dir : artifacts/data_ingestion
  bucket_name : cricket-frame-dataset
  bucket_folder_name: Dataset


model_training:
  root_dir : artifacts/models
  training_data_yaml_dir : ../../../artifacts/data_ingestion/data.yaml
  yolo_pretrained_weight_name : yolov8x.pt
  trained_model_path : artifacts/models/best.pt
  onnx_model_path : artifacts/models/best.onnx

mlflow_config:
  tracking_uri : https://dagshub.com/go4ganics/yolo_pipeline.mlflow
  experiment_name : cricket_experiment_first_stage
  tracking_username : go4ganics
  tracking_password : 315d2db73053f9540d64aee726e2a3ea8d55d154



  
